version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aufgabenplaner
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - aufgaben-net

    

  backend:
    image: sebastianburesch/aufgabenplaner:backendapp-1.0
    container_name: backend
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/aufgabenplaner?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    networks:
      - aufgaben-net

  frontend:
    image: sebastianburesch/aufgabenplaner:frontendapp-1.0
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - aufgaben-net

volumes:
  mysql_data:

networks:
  aufgaben-net:
    driver: bridge
