version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/appdb
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

  e2e:
    image: cypress/included:13.7.3  # Use a suitable Cypress version
    depends_on:
      - frontend
      - backend
    working_dir: /e2e
    volumes:
      - ./e2e:/e2e
    environment:
      - CYPRESS_baseUrl=http://frontend:80
    command: npx cypress run

